### PR TITLE
Require min/max only for accessors containing position attributes

### LINKED ISSUE #325: Add back requireAccessorMinMax
From https://github.com/AnalyticalGraphicsInc/gltf-pipeline/pull/324

> Removed requireAccessorMinMax. This function was unsafe to use in Cesium because it required glTFs to have proper byte alignment, and glTF 1.0 models often fail to be aligned. I'll open an issue to add this functionality back.

For the 2.0 branch. Ideally no operations in gltf-pipeline should require byte alignment since we always have to worry about 1.0 models passing through, and would prefer not to copy the memory. The byte alignment condition was new to the 2.0 spec.

### PR DESCRIPTION
**Pull request by lilleyse**
Fixes #325

According to the spec: 

> POSITION accessor must have min and max properties defined.

And it is optional for other accessors.

Since `requireAccessorMinMax` is by far the slowest part of the 1.0 - 2.0 upgrade I think it makes sense to only compute the min/max when needed. This will help speed up engines using gltf-pipeline to upgrade models on the fly. In fact I had previously removed `requireAccessorMinMax` from the `cesium-2.0` branch because it was too slow.

Thankfully min/max are already present on most glTF 1.0 position accessors so `findAccessorMinMax` should not be called too often.

### CODE REVIEW

File: lib/updateVersion.js [hunk 1]
```diff
@@ -803,7 +803,8 @@ function moveByteStrideToBufferView(gltf) {
 }
 
 function requireAccessorMinMax(gltf) {
```
Comment (ggetz) [inline lib/updateVersion.js]: Might want to just clarify the helper function name here by specifying position.

**Comment by ggetz** [comment]
Thanks @lilleyse !
